source/TestCommon/documents/functionapp-testcommon.md
source/TestCommon/documents/servicebusresourceprovider.md

Add documentation of ServiceBusResourceProvider and related types.
https://app.zenhub.com/workspaces/mighty-ducks-60ae1565be2dfe0017ff66b2/issues/energinet-datahub/mightyducks/245

ServiceBusResourceProvider documentation

---

.licenserc.json
source/TestCommon/TestCommon.sln
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/FunctionAppHost/FunctionAppHostManager.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionAppHost/FunctionAppHostManagerExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionAppHost/FunctionAppHostSettings.cs
source/TestCommon/source/TestCommon/Diagnostics/TestDiagnosticsLogger.cs
source/TestCommon/source/TestCommon/TestCommon.csproj

- Extended control of starting an Azure Function App through use of the `FunctionAppHostManager`:
- Specify which functions to load using `FunctionAppHostSettings.Functions`.
- Set environment variables for the process using `FunctionAppHostSettings.ProcessEnvironmentVariables`.
- Write host process id to output when started, so we know which process to attach debugger to if needed.
- Updated default values for `FunctionAppHostSettings` to reduce the necessary settings in  `functionapphost.settings.json`.
- Implemented `FunctionAppHostManagerExtensions`:
- `CheckIfFunctionWasExecuted`
- `TriggerFunctionAsync`
https://app.zenhub.com/workspaces/mighty-ducks-60ae1565be2dfe0017ff66b2/issues/energinet-datahub/mightyducks/232

Support multi functionapp

---

source/TestCommon/documents/functionapp-testcommon.md

Updated FunctionApp.TestCommon documentation with steps for installing required tools on developer machines.

Document preparing Developer Machine

---

source/Logging/source/RequestResponseMiddleware/RequestResponseLoggingMiddleware.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

fix for logging response stream
* #0000

logging request response middleware

---

source/Logging/documents/documentation.md
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware/JwtTokenParsing.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseLoggingMiddleware.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

updated jwt parsing update with better gln lookup.
* #0000

jwt parsing update

---

source/Logging/documents/documentation.md
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware.Tests/LogDataBuilderTests.cs
source/Logging/source/RequestResponseMiddleware/AssemblyInfo.cs
source/Logging/source/RequestResponseMiddleware/LogDataBuilder.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseLoggingMiddleware.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

Added TraceId to metadata and index tags for better lookup with application insight logs.
Limited query params saved in index tags to 3.
* #0000

Added TraceId to metadata and index tags for better lookup with application insight

---

source/FunctionApp/documents/release-notes/release-notes.md
source/FunctionApp/source/Common.Abstractions/Common.Abstractions.csproj
source/FunctionApp/source/Common.SimpleInjector/Common.SimpleInjector.csproj
source/FunctionApp/source/Common/Common.csproj
source/FunctionApp/source/Common/Middleware/JwtTokenMiddleware.cs
source/FunctionApp/source/Common/Middleware/ServiceBusActorContextMiddleware.cs

Charges domain only have one az function to handle all request, and therefor this middleware must exit if the context is not a httpcontext.
* #0000

JwtTokenMiddelware returns if context is not http

---

source/FunctionApp/source/Common.Abstractions/Actor/IActorContext.cs
source/FunctionApp/source/Common.Abstractions/Common.Abstractions.csproj
source/FunctionApp/source/Common.SimpleInjector/Common.SimpleInjector.csproj
source/FunctionApp/source/Common/ActorContext.cs
source/FunctionApp/source/Common/Common.csproj
source/FunctionApp/source/Common/Middleware/Helpers/ServiceBusActorParser.cs

CurrentActor is now nullable in ActorContext.

CurrentActor is now nullable in ActorContext

---

source/FunctionApp/source/Common.Abstractions/Common.Abstractions.csproj
source/FunctionApp/source/Common.SimpleInjector/Common.SimpleInjector.csproj
source/FunctionApp/source/Common/Common.csproj
source/FunctionApp/source/Common/Middleware/ActorMiddleware.cs
source/FunctionApp/source/Common/Middleware/JwtTokenMiddleware.cs
source/FunctionApp/source/Common/Middleware/ServiceBusActorContextMiddleware.cs

Both JWTToken / ServiceBusActorMiddelware exited their context and never called next.
* #0000

bug: exiting middelware too early

---

source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Abstractions/Users/IUserContext.cs
source/App/source/Common.Abstractions/Users/IUserProvider.cs
source/App/source/Common.Abstractions/Users/User.cs
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/Common/UserContext.cs
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/ContainerExtensions.cs
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/Middleware/UserMiddleware.cs
source/App/source/WebApp/WebApp.csproj

Add UserMiddleware and friends

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Abstractions/Users/User.cs
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

User has a list of actorids

---

source/App/source/FunctionApp/Extensions/FunctionContextExtensions.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/FunctionApp/Middleware/ActorMiddleware.cs
source/App/source/FunctionApp/Middleware/JwtTokenMiddleware.cs
source/App/source/FunctionApp/Middleware/ServiceBusActorContextMiddleware.cs
source/App/source/FunctionApp/TriggerType.cs

Adds more (generic) checks for trigger type in middlewares.

add trigger type check

---

source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Bump App versions

---

source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj

Does what it says in the title👆

bump version in functionapp

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Only verify version number on PR build, if content has changed.
(https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/225)

Verify version number on PR if content has changed 

---

.github/workflows/app-common-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/Extensions/FunctionContextExtensions.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Fixes the `FunctionContextExtensions.Is` method so that it correctly detects e.g. HttpTrigger.

App bundle fix

---

source/App/documents/health-checks.md
source/App/documents/release-notes/release-notes.md

Updated release notes (will not need to create a new package/version).

Updated release notes

---

source/App/App.sln
source/App/documents/health-checks.md
source/App/source/FunctionApp/Diagnostics/HealthChecks/IHealthCheckEndpointHandler.cs

Update health check documentation.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/56

App documentation - update health check parts

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/AzureB2CSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Extend classes to support testing using an Azure AD B2C tenant created in the "integration test" environment.

Integrationtest B2C support

---

source/App/App.sln
source/App/documents/documentation.md
source/App/documents/functionTelemetryScopeMiddleware.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/FunctionApp/Middleware/FunctionTelemetryScopeMiddleware.cs
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Another feature used and therefore duplicated across domains is the need to handle the `TelemetryDependcy`'s.
This PR will add the middleware FunctionTelemetryScopeMiddleware to the `Energinet.DataHub.Core.App` package.

Add: Function telemetry scope middleware

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware.Tests/LocalLog.cs
source/Logging/source/RequestResponseMiddleware.Tests/LocalLogStorage.cs
source/Logging/source/RequestResponseMiddleware.Tests/LogDataBuilderTests.cs
source/Logging/source/RequestResponseMiddleware.Tests/LogTagsTests.cs
source/Logging/source/RequestResponseMiddleware.Tests/MockJwtTokens.cs
source/Logging/source/RequestResponseMiddleware.Tests/MockedFunctionContext.cs
source/Logging/source/RequestResponseMiddleware.Tests/MockedHttpRequestData.cs
source/Logging/source/RequestResponseMiddleware.Tests/RequestResponseLoggingMiddlewareTests.cs
source/Logging/source/RequestResponseMiddleware/LogDataBuilder.cs
source/Logging/source/RequestResponseMiddleware/LogInformation.cs
source/Logging/source/RequestResponseMiddleware/Models/IndexTagsKeys.cs
source/Logging/source/RequestResponseMiddleware/Models/LogTags.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseLoggingMiddleware.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj
source/Logging/source/RequestResponseMiddleware/Storage/IRequestResponseLogging.cs
source/Logging/source/RequestResponseMiddleware/Storage/RequestResponseLoggingBlobStorage.cs

Request Response logging - bug fixes and refactor
* #0000

Request Response logging - bug fixes and refactor

---

source/TestCommon/documents/development.md
source/TestCommon/documents/functionapp-testcommon.md

Add note that that explains what to do if you get Status: 403 (Forbidden) when running integration tests in Rider
Add a note that describes how to fix Status: 403 (Forbidden) when running integration tests in Rider
* #0000

Add note to setup local environment

---

source/App/documents/release-notes/release-notes.md
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/FunctionApp/Middleware/ActorMiddleware.cs
source/App/source/FunctionApp/Middleware/JwtTokenMiddleware.cs

Introduced ability to create ActorMiddleware with exclusion of specific functions. This is commonly used when implementing HealthCheck in functions.
* #0000

feat: add exclusion list for ActorMiddleware

---

source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Fix missing alignment in #108
* #0000

fix: align nuget package version numbers to 2.3.3

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware/RequestResponseLoggingMiddleware.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

bug fix uniquelogname

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

TestCommon: 
- Use new action for dotnet setup and tools
Might have to update version, if other PR i merged first.
Depends on: https://github.com/Energinet-DataHub/.github/pull/99

TestCommon: Reuse actions

---

.github/workflows/app-common-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Use composite actions for reusability.

Use composite actions

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Code coverage flags

---

.github/workflows/logging-bundle-publish.yml
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

Logging: use composite actions

---

.github/workflows/messaging-bundle-publish.yml
source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Messaging.Integration.ServiceCollection/Messaging.Integration.ServiceCollection.csproj
source/Messaging/source/Messaging.Protobuf.Integration.ServiceCollection/Messaging.Protobuf.Integration.ServiceCollection.csproj
source/Messaging/source/Messaging.Protobuf/Messaging.Protobuf.csproj
source/Messaging/source/Messaging/Messaging.csproj

Messaging: Use composite actions

---

.github/workflows/schemas-bundle-publish.yml
codecov.yml
source/Schemas/documents/release-notes/release-notes.md
source/Schemas/source/Schemas/Schemas.csproj

Schemas: use composite actions

---

source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization.Tests/JsonSerializerTests.cs
source/JsonSerialization/source/JsonSerialization/IJsonSerializer.cs
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj
source/JsonSerialization/source/JsonSerialization/JsonSerializer.cs

Add serializer that serialize to stream

---

.github/workflows/app-common-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Upgrade all .NET projects from .NET 5 to .NET 6

Upgrade App to .NET 6

---

.github/workflows/app-common-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/FunctionApp.TestCommon.Tests.csproj
source/TestCommon/source/TestCommon.Tests/TestCommon.Tests.csproj

Upgrade TestCommon to .NET 6

---

.github/workflows/featuremanagement-ci.yml
source/FeatureManagement/source/SampleApp.Tests/Fixtures/SampleFunctionAppFixture.cs
source/FeatureManagement/source/SampleApp.Tests/SampleApp.Tests.csproj
source/FeatureManagement/source/SampleApp.Tests/functionapphost.settings.json
source/FeatureManagement/source/SampleApp/SampleApp.csproj

Upgrade FeatureManagement from .NET 5 to .NET 6

Upgrade FeatureManagement from .NET 5 to .NET 6

---

source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization.Tests/JsonSerialization.Tests.csproj
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj

Upgrade testproject from .NET 5 to .NET 6

Upgrade JsonSerialization from .NET 5 to .NET 6

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware.Tests/RequestResponseMiddleware.Tests.csproj
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

Upgrade Logging from .NET 5 to .NET 6

---

source/Schemas/documents/release-notes/release-notes.md
source/Schemas/source/Schemas/Schemas.csproj

Upgrade Schemas from .NET 5 to .NET 6

Upgrade Schemas from .NET 5 to .NET 6

---

source/XmlConversion/documents/release-notes/release-notes.md
source/XmlConversion/source/XmlConverter.Abstractions/XmlConverter.Abstractions.csproj
source/XmlConversion/source/XmlConverter.SimpleInjector/XmlConverter.SimpleInjector.csproj
source/XmlConversion/source/XmlConverter.Tests/XmlConverter.Tests.csproj
source/XmlConversion/source/XmlConverter/XmlConverter.csproj

Upgrade XmlConverter from .NET 5 to .NET 6

Upgrade XmlConverter from .NET 5 to .NET 6

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/RequestResponseMiddleware.Tests/LogDataBuilderTests.cs
source/Logging/source/RequestResponseMiddleware.Tests/LogTagsTests.cs
source/Logging/source/RequestResponseMiddleware.Tests/RequestResponseLoggingMiddlewareTests.cs
source/Logging/source/RequestResponseMiddleware/LogDataBuilder.cs
source/Logging/source/RequestResponseMiddleware/Models/LogInformation.cs
source/Logging/source/RequestResponseMiddleware/Models/LogTags.cs
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

Updated Azure.Blob SDK.
Refactored the way query params are parsed because when request body contained Json it was added to BindingData along with query params. That made a meta data for blob storage that was too large.
* #0000

Updated Logging for Json Body Bug

---

source/App/documents/development.md
source/App/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj
source/App/source/ExampleHost.FunctionApp.Tests/Fixtures/ExampleHostFixture.cs
source/App/source/ExampleHost.FunctionApp.Tests/Integration/ExampleHostTests.cs
source/App/source/ExampleHost.FunctionApp01/ExampleHost.FunctionApp01.csproj
source/App/source/ExampleHost.FunctionApp02/ExampleHost.FunctionApp02.csproj
source/App/source/ExampleHost.WebApi.Tests/ExampleHost.WebApi.Tests.csproj
source/App/source/ExampleHost.WebApi.Tests/Integration/ExampleHostTests.cs
source/App/source/ExampleHost.WebApi01/Controllers/WeatherForecastController.cs
source/App/source/ExampleHost.WebApi01/ExampleHost.WebApi01.csproj
source/App/source/ExampleHost.WebApi02/Controllers/WeatherForecastController.cs
source/App/source/ExampleHost.WebApi02/ExampleHost.WebApi02.csproj

Update NuGet packages and improve tests
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/397

Update NuGet packages and improve tests

---

source/App/App.sln
source/App/documents/documentation.md
source/App/documents/extensions.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.FunctionApp.Tests/Integration/ExampleHostTests.cs
source/App/source/ExampleHost.FunctionApp01/ExampleHost.FunctionApp01.csproj
source/App/source/ExampleHost.FunctionApp01/Program.cs
source/App/source/ExampleHost.FunctionApp02/Program.cs
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp.Tests/Middleware/CorrelationId/TraceParentTests.cs
source/App/source/FunctionApp/Extensions/DependencyInjection/ApplicationInsightsExtensions.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/FunctionApp/FunctionTelemetryScope/FunctionTelemetryScopeMiddleware.cs
source/App/source/FunctionApp/FunctionTelemetryScope/TraceParent.cs
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

* Clean up in comments
* Add FunctionApp tests that set `traceparent` header
* Rename `TraceContext` to `TraceParent`
* Added Function App extension `AddApplicationInsights`
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/346

Tracecontext extension

---

source/App/documents/health-checks.md

Update health check walk through

---

source/App/documents/development.md
source/App/source/ExampleHost.FunctionApp.Tests/Fixtures/ExampleHostFixture.cs

Bug in VS 2022 17.3.x has been fixed

---

.github/workflows/app-common-bundle-publish.yml
.github/workflows/testcommon-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/607

Use same environment name as other repositories

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Actors/IdentificationType.cs
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Fixed renaming missed namespace

---

.github/workflows/json-serialization-bundle-publish.yml
source/JsonSerialization/JsonSerialization.sln.DotSettings
source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization/IJsonSerializer.cs
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj
source/JsonSerialization/source/JsonSerialization/JsonSerializer.cs

Add method to `IJsonSerializer`:
```csharp
/// <summary>
/// Parse the value representing a single JSON value into an object of the type <typeparam name="T" />.
/// </summary>
public Task<T> DeserializeAsync<T>(byte[] data);
```

feat: Add JSON deserialization of byte[]

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/integrationtest.local.settings.sample.json
source/TestCommon/source/FunctionApp.TestCommon/Configuration/B2C/B2CAuthorizationConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Refactor to use new setting named AZURE_B2CSECRETS_KEYVAULT_URL
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/720

Use new setting name

---

.github/workflows/app-common-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common.Tests/integrationtest.local.settings.sample.json
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj
source/App/source/ExampleHost.WebApi.Tests/ExampleHost.WebApi.Tests.csproj
source/App/source/ExampleHost.WebApi.Tests/integrationtest.local.settings.sample.json
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Some secrets/settings has been renamed.
The patch version of the App packages has been updated because the YML file has been changed. Its important to understand that test dependencies has changed, but tests are not part of the package so this does NOT impact the package and hence we do not bump a major version.
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/720

App package: Cleanup secrets

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common.Security/Permission.cs
source/App/source/Common.Security/PermissionsAsClaims.cs
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

New permission to control access to creating/editing userroles

Added new permission

---

source/App/documents/authorization.md

update permission documentation when adding new permission, added "Created"
* #0000

update permission documentation

---

CODEOWNERS

https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1207

renamed batman to phoenix

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Azurite/AzuriteManagerTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/DatabricksSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/DatabricksWarehouseSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1217

Support settings for Databricks SQL Warehouse

---

.github/workflows/featuremanagement-ci.yml

Reference: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1249

Use v12 of .github

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/Azurite/TestCertificate/ReadMe.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Added command to update certificate

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.WebApi.Tests/Fixtures/ExampleHostFixture.cs
source/App/source/ExampleHost.WebApi.Tests/Integration/ExampleHostTests.cs
source/App/source/ExampleHost.WebApi01/ExampleHost.WebApi01.csproj
source/App/source/ExampleHost.WebApi01/SomeTrigger.cs
source/App/source/ExampleHost.WebApi01/Startup.cs
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/Diagnostics/HealthChecks/RepeatingTriggerHealthCheck.cs
source/App/source/WebApp/Hosting/RepeatingTrigger.cs
source/App/source/WebApp/WebApp.csproj

fix: Fix health monitoring of `RepeatingTrigger`

---

.github/workflows/databricks-bundle-publish.yml

The path was wrong. Additionally changed some descriptions.
* #0000

fix: Databricks publish workflow

---

.github/workflows/databricks-bundle-publish.yml
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

use new integration test env

---

documents/development.md

Updated with project file properties needed for a package.
* #0000

docs: Update development documentation

---

.github/workflows/logging-bundle-publish.yml
codecov.yml
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/LoggingScopeMiddleware/LoggingScopeMiddleware.csproj
source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj

Add LoggingScopeMiddleware project to Workflow.
* #0000

Add LoggingScopeMiddleware project to workflow

---

.github/CODEOWNERS

Added Henrik Sommer as codeowner

Added Henrik Sommer as codeowner

---

source/Databricks/documents/documentation.md
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.UnitTests/Extensions/DependencyInjection/JobsExtensionsTests.cs
source/Databricks/source/Jobs/Extensions/DependencyInjection/JobsExtensions.cs
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Moved the options binding to GEH Core and corrected the tests.

refac: Moved Databricks Jobs options bind to GEH Core.

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.UnitTests/Extensions/DependencyInjection/JobsExtensionsTests.cs
source/Databricks/source/Jobs.UnitTests/Internal/JobsApiClientTests.cs
source/Databricks/source/Jobs/Extensions/DependencyInjection/JobsExtensions.cs
source/Databricks/source/Jobs/Internal/Constants/HttpClientNameConstants.cs
source/Databricks/source/Jobs/Internal/JobsApiClient.cs
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

- Now HttpClientFactory is inject into JobsApiClient
- Added tests of the resolving of http client in JobsApiClient
- DatabricksJobsOption is now bund in the registration class (JobsExtensions)

refac: http factory client is injected into JobsAPiClient.

---

source/TestCommon/source/TestCommon.Tests/Unit/AutoFixture/AutoFixtureExtensionsTests.cs

Added a few tests to prove the behavior of the AutoFixture extensions.
Note that updating tests will not require us to bump package versions.

AutoFixture extensions: Add tests

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.IntegrationTests/Jobs.IntegrationTests.csproj
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/SqlStatementExecution.IntegrationTests.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Update SqlStatement and Jobs to use nugetpackage funcapp in testcommon v.4.4.2

fix: update nugetpackages in SqlStatement and Jobs

---

source/Databricks/documents/documentation.md
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/DatabricksSqlWarehouseQueryExecutor.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Support for mocking with protected / virtual members

Support mocking with procted/virtual members

---

.github/workflows/ci-orchestrator.yml

use new consolidated github pat

use new github secret pat

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/ApacheArrowTimeStampTests.cs
source/Databricks/source/SqlStatementExecution/Formats/IArrowArrayExtensions.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Fix bug in timestamp conversion

Fix timestamp in Databricks statement

---

source/Databricks/documents/documentation.md
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/DatabricksStatementsTests.cs
source/Databricks/source/SqlStatementExecution/Formats/IArrowArrayExtensions.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Support reading data where a column contains an array.

Databricks client - Add support for array type

---

.github/workflows/ci-orchestrator.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Abstractions/Users/IUserProvider.cs
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.WebApi04/Security/ExampleDomainUserProvider.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/Middleware/UserMiddleware.cs
source/App/source/WebApp/WebApp.csproj

Rename field to better match concept.

Update parameter from isFas to multiTenancy.

---

.github/workflows/app-common-bundle-publish.yml
.github/workflows/databricks-bundle-publish.yml
.github/workflows/json-serialization-bundle-publish.yml
.github/workflows/logging-bundle-publish.yml
.github/workflows/messaging-bundle-publish.yml
.github/workflows/testcommon-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/WebApp.csproj
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj
source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Messaging/Messaging.csproj
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/FunctionApp.TestCommon.Tests.csproj
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1813
Bonus:

Remove  code_coverage_flags parameter

---

.github/workflows/detect-changes.yml

Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1911

Bump versions to remove Node16 warnings

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/app-common-bundle-publish.yml
.github/workflows/ci-orchestrator.yml
.github/workflows/databricks-bundle-publish.yml
.github/workflows/featuremanagement-ci.yml
.github/workflows/json-serialization-bundle-publish.yml
.github/workflows/logging-bundle-publish.yml
.github/workflows/messaging-bundle-publish.yml
.github/workflows/testcommon-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/WebApp.csproj
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj
source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Messaging/Messaging.csproj
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1879

Bump .github v12 --> v13

---

.github/CODEOWNERS

Added Rasmus and Michael as codewoners

---

README.md
docs/development.md
source/App/documents/development.md

Update various documentation in geh-core to match actual use and location of files/projects.

App: Update docs

---

source/App/Directory.Build.props
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common.Tests/Users/UserContextTests.cs
source/App/source/Common/Common.csproj
source/App/source/Common/Users/UserContext.cs
source/App/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj
source/App/source/ExampleHost.FunctionApp.Tests/Fixtures/ExampleHostsFixture.cs
source/App/source/ExampleHost.WebApi.Tests/ExampleHost.WebApi.Tests.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.Tests/WebApp.Tests.csproj
source/App/source/WebApp/Authentication/AuthenticationExtensions.cs
source/App/source/WebApp/Middleware/UserMiddleware.cs
source/App/source/WebApp/WebApp.csproj

Upgrade App to .net 8.

---

source/App/documents/registrations/telemetry.md

Use correct casing of DataHub in documentation

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/EventHubListenerMockFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/EventHubResourceProviderFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/ServiceBusListenerMockFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/ServiceBusResourceProviderFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/SingletonIntegrationTestConfiguration.cs

Verify new action version

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IConfigurationBuilderExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

feat: IntegrationTestConfiguration - supply-default-azure-credentials

---

.github/workflows/codeql-databricks.yml

Configure codeql for data bricks

Add codeql file for databricks

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/FunctionApp.TestCommon.Tests.csproj
source/TestCommon/source/FunctionApp.TestCommon/Databricks/DatabricksSchemaManagerExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon.Tests/TestCommon.Tests.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Related to:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/228

TestCommon: Add DatabricksSchemaManager extensions

---

source/App/source/ExampleHost.FunctionApp.Tests/Fixtures/ExampleHostsFixture.cs
source/App/source/ExampleHost.WebApi.Tests/Fixtures/AuthenticationHostFixture.cs
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Testing app. registrations made in Terraform in [dh3-infrastructure PR-1613](https://github.com/Energinet-DataHub/dh3-infrastructure/pull/1613) rather than ClickOps ones
Reference: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1967

TestCommon: Using app registrations created by IaC

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/ApacheArrowArrayTests.cs
source/Databricks/source/SqlStatementExecution/Formats/IArrowArrayExtensions.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

The code wasn't able to handle an odd number of columns and would return in very spectacular ways. New testscases have been added to reflect this behaviour.

Fix bug in handling of arrays

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/WebApp.csproj

Try out preview of DarkLoop to get a fix for [issue](https://github.com/dark-loop/functions-authorize/issues/62).

Use latest version of DarkLoop

---

source/Databricks/source/Jobs.IntegrationTests/Jobs.IntegrationTests.csproj
source/Databricks/source/Jobs.UnitTests/Diagnostics/HealthChecks/DatabricksJobsApiHealthCheckTests.cs
source/Databricks/source/Jobs.UnitTests/Jobs.UnitTests.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Fixtures/DatabricksSqlWarehouseFixture.cs
source/Databricks/source/SqlStatementExecution.IntegrationTests/SqlStatementExecution.IntegrationTests.csproj
source/Databricks/source/SqlStatementExecution.UnitTests/Diagnostics/HealthChecks/DatabricksSqlStatementApiHealthCheckTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/SqlStatementExecution.UnitTests.csproj

Updated TestCommon nuget usages to 6.1.0

---

source/App/documents/documentation.md
source/App/documents/registrations/health-checks.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/Common/Diagnostics/HealthChecks/HealthChecksConstants.cs
source/App/source/ExampleHost.FunctionApp.Tests/Integration/HealthChecksTests.cs
source/App/source/ExampleHost.FunctionApp01/Program.cs
source/App/source/ExampleHost.WebApi.Tests/Integration/HealthChecksTests.cs
source/App/source/ExampleHost.WebApi01/Startup.cs
source/App/source/FunctionApp/Diagnostics/HealthChecks/HealthCheckEndpointHandler.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.Tests/Extensions/Builder/HealthCheckEndpointRouteBuilderExtensionsTests.cs
source/App/source/WebApp.Tests/Fixtures/HealthChecksFixture.cs
source/App/source/WebApp/Extensions/Builder/HealthCheckEndpointRouteBuilderExtensions.cs
source/App/source/WebApp/WebApp.csproj

See title.
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/241

feat: Extend health checks with "status" endpoint

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/documents/servicebuslistenermock.md
source/TestCommon/documents/servicebusresourceprovider.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/ServiceBusListenerMockFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/ServiceBusResourceProviderFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/ServiceBus/ListenerMock/ServiceBusListenerMockTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/ServiceBus/ResourceProvider/ServiceBusResourceProviderTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/ServiceBus/ListenerMock/ServiceBusListenerMock.cs
source/TestCommon/source/FunctionApp.TestCommon/ServiceBus/ResourceProvider/ServiceBusResourceProvider.cs
source/TestCommon/source/TestCommon/TestCommon.csproj

Refactor ServiceBus code to support IAM.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/293

refac: ServiceBus IAM

---

source/App/documents/registrations/swagger-api-version.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.WebApi.Tests/Integration/SwaggerOpenApiTests.cs
source/App/source/ExampleHost.WebApi01/Common/EnumTest.cs
source/App/source/ExampleHost.WebApi01/Controllers/SwaggerDisplayController.cs
source/App/source/ExampleHost.WebApi01/Controllers/SwaggerHandleEnumController.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/Extensibility/Swashbuckle/EnumExtensionSchemaFilter.cs
source/App/source/WebApp/Extensibility/Swashbuckle/EnumOpenApiExtension.cs
source/App/source/WebApp/Extensions/DependencyInjection/OpenApiExtensions.cs
source/App/source/WebApp/WebApp.csproj

Added x-enumNames to swagger output

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/Databricks/source/SqlStatementExecution/Statement/DatabricksStatementRequest.cs

With the merge of this PR we should see some more meaning full errors compared to what is being thrown today.

Add check for valid delay input

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/DatabricksStatementsTests.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Skip tests since the need for downloading 2GB data is no longer relevant.

Skip tests: We don't have a need for results of this size

---

.github/workflows/outbox-bundle-publish.yml

Add ´.github/workflows/outbox-bundle-publish.yml´ to enable prerelease of package

feat: Add outbox-bundle-publish workflow

---

source/Logging/documents/documentation.md

Fix rendering of C# code blocks
Original contributed by @NielsPilgaard in PR [354](https://github.com/Energinet-DataHub/geh-core/pull/354)

Update logging documentation.md

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.WebApi.Tests/Integration/SwaggerOpenApiTests.cs
source/App/source/ExampleHost.WebApi01/Startup.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/Extensions/DependencyInjection/OpenApiExtensions.cs
source/App/source/WebApp/Extensions/Options/ConfigureSwaggerOptions.cs
source/App/source/WebApp/Extensions/Options/SwaggerUIOptions.cs
source/App/source/WebApp/WebApp.csproj

Add support for optional SwaggerUI description in WebApi.

Add support for optional SwaggerUI description in WebApi

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj
source/App/source/ExampleHost.FunctionApp01/ExampleHost.FunctionApp01.csproj
source/App/source/ExampleHost.FunctionApp02/ExampleHost.FunctionApp02.csproj
source/App/source/ExampleHost.WebApi.Tests/ExampleHost.WebApi.Tests.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.Tests/WebApp.Tests.csproj
source/App/source/WebApp/WebApp.csproj

chore: updating nuget packages in app

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.IntegrationTests/Jobs.IntegrationTests.csproj
source/Databricks/source/Jobs.UnitTests/Jobs.UnitTests.csproj
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/SqlStatementExecution.IntegrationTests.csproj
source/Databricks/source/SqlStatementExecution.UnitTests/SqlStatementExecution.UnitTests.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

chore: updating nuget packages in databricks

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/FunctionApp.TestCommon.Tests.csproj
source/TestCommon/source/FunctionApp.TestCommon/Database/SqlServerDatabaseManager.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon.Tests/TestCommon.Tests.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

chore: updating nuget packages in test common

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging.Tests/Logging.Tests.csproj
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware.Tests/LoggingMiddleware.Tests.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj

chore: updating nuget packages in logging

---

source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization.Tests/JsonSerialization.Tests.csproj
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj
source/JsonSerialization/source/JsonSerialization/JsonSerializer.cs

chore: updating nuget packages in json serialization

---

.github/dependabot.yml
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

TestCommon: Update NuGet packages

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.IntegrationTests/Jobs.IntegrationTests.csproj
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/SqlStatementExecution.IntegrationTests.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

chore: Upgrade NuGet packages in Databricks

---

source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Communication.UnitTests/Communication.UnitTests.csproj
source/Messaging/source/Communication/Communication.csproj
source/Messaging/source/ExampleHost.FunctionApp/ExampleHost.FunctionApp.csproj

chore: Upgrade NuGet packages in Messaging

---

source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization.Tests/JsonSerialization.Tests.csproj
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj

chore: Upgrade NuGet packages in JsonSerialization

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj

chore: Upgrade NuGet packages in Logging

---

source/Outbox/source/ExampleHost.WebApi/ExampleHost.WebApi.csproj

chore: Upgrade NuGet packages in Outbox

---

source/FeatureManagement/source/SampleApp.Tests/SampleApp.Tests.csproj

chore: Upgrade NuGet packages in FeatureManagement

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/FunctionApp.TestCommon.Tests.csproj
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon.Tests/TestCommon.Tests.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

chore: Upgrade NuGet packages in TestCommon

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon.Tests/DurableClientExtensionsTests.cs
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableTask/DurableClientExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Fix error in durable function extension when waiting for orchestration to start.
- Used in PM: https://github.com/Energinet-DataHub/opengeh-process-manager/pull/30
- Used in EDI: https://github.com/Energinet-DataHub/opengeh-edi/pull/1415

fix: Fix durable function extension error when waiting for orchestration to start

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon.Tests/DurableClientExtensionsTests.cs
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableTask/DurableClientExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/474

feat: Extend DurableClientExtensions

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableTask/DurableClientExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

fix: DurableClientExtensions method WaitForOrchestationStartedAsync

---

.github/CODEOWNERS
.github/workflows/ci-orchestrator.yml

Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2786

Support merge queues

---

.github/CODEOWNERS

https://app.zenhub.com/workspaces/team-fusion-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2847

2847-removeOutlawsAndRatatosk

---

.github/workflows/app-common-bundle-publish.yml
.github/workflows/databricks-bundle-publish.yml
.github/workflows/json-serialization-bundle-publish.yml
.github/workflows/logging-bundle-publish.yml
.github/workflows/messaging-bundle-publish.yml
.github/workflows/outbox-bundle-publish.yml
.github/workflows/testcommon-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/WebApp.csproj
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/JsonSerialization/documents/release-notes.md
source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj
source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Communication/Communication.csproj
source/Messaging/source/ExampleHost.FunctionApp/ExampleHost.FunctionApp.csproj
source/Outbox/documents/release-notes.md
source/Outbox/source/Outbox.Abstractions/Outbox.Abstractions.csproj
source/Outbox/source/Outbox/Outbox.csproj
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

https://github.com/tj-actions/changed-files/issues/2463#issuecomment-2727015784

Update tj-actions/changed-files to v46.0.1

---

source/TestCommon/documents/development.md
source/TestCommon/documents/functionapp-testcommon.md
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/AppConfigurationManagerFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/AppConfiguration/AppConfigurationManagerTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/IntegrationTestConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon/AppConfiguration/AppConfigurationManager.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/712

feat: Support use of Azure App Configuration in integration tests

---

source/App/documents/documentation.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.FunctionApp.Tests/Integration/FeatureManagementTests.cs
source/App/source/ExampleHost.FunctionApp01/ExampleHost.FunctionApp01.csproj
source/App/source/ExampleHost.FunctionApp01/Functions/DurableFunction.cs
source/App/source/ExampleHost.FunctionApp01/Functions/FeatureManagementFunction.cs
source/App/source/ExampleHost.FunctionApp01/Program.cs
source/App/source/FunctionApp/Extensions/Builder/ApplicationBuilderExtensions.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/FunctionApp/Middleware/AzureAppConfigurationRefreshMiddleware.cs
source/App/source/WebApp/WebApp.csproj

See title.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/736

feat: Custom registration of Azure App Configuration middleware for functions

---

source/App/documents/registrations/feature-management.md

See title.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/713

chore: Feature Management - Update documentation with links to code

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/Configuration/SubsystemAuthenticationOptionsForTests.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

See title or readme.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/755

TestCommon: Subsystem Authentication options for tests

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.IntegrationTests/Jobs.IntegrationTests.csproj
source/Databricks/source/Jobs.UnitTests/Jobs.UnitTests.csproj
source/Databricks/source/Jobs/Http/IntegrationTestingEnvironmentTokenProvider.cs
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/SqlStatementExecution.IntegrationTests.csproj
source/Databricks/source/SqlStatementExecution.UnitTests/SqlStatementExecution.UnitTests.csproj
source/Databricks/source/SqlStatementExecution/Http/IntegrationTestingEnvironmentTokenProvider.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

This pull request includes updates to dependency versions and a minor adjustment to the credential configuration in the `IntegrationTestingEnvironmentTokenProvider`. Below are the most important changes:
* Updated multiple NuGet package dependencies in `Jobs` and `SqlStatementExecution.csproj` to newer versions, including `Apache.Arrow` (18.1.0 → 20.0.0), `Azure.Identity` (1.13.2 → 1.14.0), and several `Microsoft.Extensions.*` packages (8.x → 9.x). These updates likely include bug fixes, performance improvements, and new features.

Upgrade dependencies in Databricks

---

source/Messaging/documents/documentation.md

See title.
Since we only update documentation, this will not require a new deployment of the package - so version and release notes should not be updated.

Messaging documentation fix

---

.github/workflows/messaging-bundle-publish.yml
source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Communication.IntegrationTests/Communication.IntegrationTests.csproj
source/Messaging/source/Communication/Communication.csproj
source/Messaging/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj

See title.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/680

Messaging: Use latest TestCommon and Azure Functions Core Tool
