Energinet-DataHub/geh-core

source/TestCommon/documents/functionapp-testcommon.md

Azure CLI version 2.3 and higher is (still) not supported for `az login` in JetBrains Rider. This pull request updates the  TestCommon documentation with a link to the latest supported version.

Link to supported Azure CLI in TestCommon documentation

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/documents/testcommon.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Database/SqlServerConnectionStringProviderTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Database/SqlServerConnectionStringProvider.cs
source/TestCommon/source/FunctionApp.TestCommon/Database/SqlServerDatabaseManager.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/RuntimeEnvironment.cs
source/TestCommon/source/TestCommon/TestCommon.csproj

Adds an option to override the default connection string. This is done by setting an environment variable.

Overwrite default sql server connection string

---

source/SchemaValidation/documents/release-notes/release-notes.md
source/SchemaValidation/source/SchemaValidation.Tests/SchemaValidatingReaderErrorExtensionsTests.cs
source/SchemaValidation/source/SchemaValidation/Errors/Error.cs
source/SchemaValidation/source/SchemaValidation/SchemaValidation.csproj

According to the business (Christian, SME),
the `code` to be returned on schema validation error is `B2B-005`, not `BadArgument` which is currently used.
This PR changes the code to `B2B-005`.
https://github.com/Energinet-DataHub/geh-charges/issues/1316

Fix: Change schema validation error code to `B2B-005` instead of `BadArgument`

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

The buildversion 2.4.4 already exists on nuget.org - our CI should fail the build, but it doesn't ??

Test that CI checks nuget.org for already existing version number

---

source/SchemaValidation/documents/release-notes/release-notes.md
source/SchemaValidation/source/SchemaValidation.Tests/SchemaValidation.Tests.csproj
source/SchemaValidation/source/SchemaValidation/SchemaValidation.csproj

Upgrade SchemaValidation from .NET 5 to .NET 6

Upgrade SchemaValidation from .NET 5 to .NET 6

---

.github/workflows/app-common-bundle-publish.yml
.github/workflows/testcommon-bundle-publish.yml
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

The two pipelines calls the action `dotnet-solution-build-and-test`. In version 7.7.0 this action logged into Azure using a SPN secret. In version 7.8.0 it authentication is based on OIDC

Update Test common and App Common to use new version of actions in pipeline

---

source/App/documents/correlationIdMiddleware.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.SimpleInjector/FunctionApp.SimpleInjector.csproj
source/App/source/FunctionApp.Tests/Middleware/CorrelationIdMiddlewareTests.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/FunctionApp/Middleware/CorrelationId/CorrelationIdMiddleware.cs
source/App/source/WebApp.SimpleInjector/WebApp.SimpleInjector.csproj
source/App/source/WebApp/WebApp.csproj

Rename Correlation-ID header to CorrelationId to match the header name used by customers.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/440

App: Rename correlation id header

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/TestCommon.sln
source/TestCommon/documents/b2ctokenretrieval.md
source/TestCommon/documents/functionapp-testcommon.md
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/B2CFixture.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/B2C/B2CAppAuthenticationClientTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Configuration/B2C/B2CAuthorizationConfigurationTests.cs
source/TestCommon/source/FunctionApp.TestCommon.Tests/integrationtest.local.settings.sample.json
source/TestCommon/source/FunctionApp.TestCommon/Configuration/AzureB2CSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/B2C/B2CAppAuthenticationClient.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/B2C/B2CAppSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/B2C/B2CAuthorizationConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/B2C/B2CClientAppCredentialsSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/Configuration/B2C/B2CClientAppSettings.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Move reusable code for B2C test support to Test Common NuGet bundle.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/413

Support B2C tests

---

source/TestCommon/TestCommon.sln.DotSettings
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/documents/servicebusresourceprovider.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/ServiceBus/ResourceProvider/ServiceBusResourceProviderTests.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/ServiceBus/ResourceProvider/TopicSubscriptionBuilder.cs
source/TestCommon/source/FunctionApp.TestCommon/ServiceBus/ResourceProvider/TopicSubscriptionBuilderExtensions.cs
source/TestCommon/source/TestCommon/TestCommon.csproj

Add an extension method to filter ServiceBus subscriptions by message type.
The implementation adheres to ADR-008.

feat: Add extension to filter ServiceBus subscriptions by message type

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/SqlStatementExecution/Internal/SqlStatementClient.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Needed to log the state of the databricksSqlResponse in order to test below referenced story. This would make sense to keep, hence this PR.
* https://github.com/Energinet-DataHub/team-volt/issues/50

DatabricksSqlStatement package: Add additional log statement to get the `DatabricksSqlResponse.State`

---

source/Logging/documents/documentation.md
source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj
source/Logging/source/LoggingMiddleware/Registration.cs

I had problems getting my Function App to show "Information" logs in Application Insights.
It turned out that a rule should be removed and then add a new filter in the code. It is a bit different compared to the WebApp, where log level is set in the AppSettings.
* #0000

feat: Logging middleware AI log level

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs.UnitTests/Client/JobsApiClientTests.cs
source/Databricks/source/Jobs.UnitTests/Extensions/DependencyInjection/DatabricksJobsExtensionsTests.cs
source/Databricks/source/Jobs/Client/JobsApiClient.cs
source/Databricks/source/Jobs/Constants/HttpClientNameConstants.cs
source/Databricks/source/Jobs/Extensions/DependencyInjection/DatabricksJobsExtensions.cs
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/DatabricksSqlStatementClientTests.cs
source/Databricks/source/SqlStatementExecution.IntegrationTests/Fixtures/DatabricksSchemaManager.cs
source/Databricks/source/SqlStatementExecution.IntegrationTests/Fixtures/DatabricksSqlStatementApiFixture.cs
source/Databricks/source/SqlStatementExecution.UnitTests/AppSettings/DatabricksSqlStatementOptionsTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/Builders/DatabricksSqlStatementClientBuilder.cs
source/Databricks/source/SqlStatementExecution.UnitTests/Client/DatabricksSqlStatementClientTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/Extensions/DependencyInjection/DatabricksSqlStatementExecutionExtensionsTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/ResponseParsers/SqlChunkDataResponseParserTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/ResponseParsers/SqlChunkResponseParserTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/ResponseParsers/SqlResponseParserTests.cs
source/Databricks/source/SqlStatementExecution/Abstractions/IDatabricksSqlStatementClient.cs
source/Databricks/source/SqlStatementExecution/Client/DatabricksSqlStatementClient.cs
source/Databricks/source/SqlStatementExecution/Constants/HttpClientNameConstants.cs
source/Databricks/source/SqlStatementExecution/Exceptions/DatabricksSqlException.cs
source/Databricks/source/SqlStatementExecution/Extensions/DependencyInjection/DatabricksSqlStatementExecutionExtensions.cs
source/Databricks/source/SqlStatementExecution/Models/SqlStatementParameter.cs
source/Databricks/source/SqlStatementExecution/ResponseParsers/SqlChunkDataResponseParser.cs
source/Databricks/source/SqlStatementExecution/ResponseParsers/SqlChunkResponseParser.cs
source/Databricks/source/SqlStatementExecution/ResponseParsers/SqlResponseParser.cs
source/Databricks/source/SqlStatementExecution/ResponseParsers/SqlStatusResponseParser.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

As suggested by @dstenroejl in [this comment](https://github.com/Energinet-DataHub/geh-core/pull/241#pullrequestreview-1639645865) on an earlier pull request, we remove the "Internal" namespace and group related code in relevant namespaces.

refac: Remove "Internal" namespace

---

source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Fixtures/DatabricksSqlWarehouseFixture.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

By cacheing our configuration we can speedup the execution of integration tests

Improve execution of integration tests

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Databricks keys in keyvault are renamed, version bump

refac: playground renamed to domain-test

---

source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Messaging/IntegrationEventServiceBusMessage.cs
source/Messaging/source/Messaging/Messaging.csproj

Add create method that uses the `ServiceBusReceivedMessage` type to the `Energinet.DataHub.Core.Messaging` package
~- [ ] Documentation is updated~ (the PR doesn't affect the current documentation)
~- [ ] Tests are implemented and executed locally~ (there are no tests in the Messaging package)

feat: Add typed create method to messaging package

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj
source/App/source/ExampleHost.FunctionApp.Tests/Fixtures/ExampleHostsFixture.cs
source/App/source/ExampleHost.FunctionApp.Tests/Integration/ExampleHostsFlowTests.cs
source/App/source/ExampleHost.FunctionApp01/Common/EnvironmentSettingNames.cs
source/App/source/ExampleHost.FunctionApp01/local.settings.sample.json
source/App/source/ExampleHost.FunctionApp02/Common/EnvironmentSettingNames.cs
source/App/source/ExampleHost.FunctionApp02/local.settings.sample.json
source/App/source/ExampleHost.WebApi.Tests/ExampleHost.WebApi.Tests.csproj
source/App/source/ExampleHost.WebApi.Tests/Fixtures/AuthenticationHostFixture.cs
source/App/source/ExampleHost.WebApi.Tests/Fixtures/AuthorizationHostFixture.cs
source/App/source/ExampleHost.WebApi.Tests/Fixtures/ExampleHostFixture.cs
source/App/source/ExampleHost.WebApi.Tests/Integration/ExampleHostTests.cs
source/App/source/ExampleHost.WebApi01/Startup.cs
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.Tests/WebApp.Tests.csproj
source/App/source/WebApp/WebApp.csproj

Enable test proving telemetry is working with application insights

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Security/Common.Security.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/Hosting/RepeatingTrigger.cs
source/App/source/WebApp/WebApp.csproj

Removed custom property "HostedService" and structured logging placeholder "Worker" from `RepeatingTrigger` because the same information is available in the property `CategoryName`.

Remove custom properties in RepeatingTrigger

---

source/Messaging/documents/release-notes/release-notes.md
source/Messaging/source/Messaging/Internal/Publisher/ServiceBusSenderProvider.cs
source/Messaging/source/Messaging/Internal/Subscriber/ServiceBusProcessorFactory.cs
source/Messaging/source/Messaging/Messaging.csproj
source/Messaging/source/Messaging/Publisher/PublisherOptions.cs
source/Messaging/source/Messaging/Subscriber/SubscriberWorkerOptions.cs

Allow setting TransportType for ServiceBus so we can get through firewall if AMQP ports are not open.

Support setting TransportType for ServiceBusClient

---

source/TestCommon/documents/eventhubresourceprovider.md
source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/EventHub/ResourceProvider/EventHubResourceProviderTests.cs
source/TestCommon/source/FunctionApp.TestCommon/EventHub/ResourceProvider/EventHubConsumerGroupBuilder.cs
source/TestCommon/source/FunctionApp.TestCommon/EventHub/ResourceProvider/EventHubConsumerGroupBuilderExtensions.cs
source/TestCommon/source/FunctionApp.TestCommon/EventHub/ResourceProvider/EventHubResource.cs
source/TestCommon/source/FunctionApp.TestCommon/EventHub/ResourceProvider/EventHubResourceBuilder.cs
source/TestCommon/source/FunctionApp.TestCommon/EventHub/ResourceProvider/IEventHubResourceBuilder.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Expanding the `EventHubResource` with possibility to add consumer groups. Based on the same builder pattern as adding subscriptions to the ServiceBus `TopicResource`.

Expand eventhub resource with possibility to add consumer groups

---

source/Databricks/documents/documentation.md
source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/DatabricksStatementsTests.cs
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/Statements/AtLeast10SecStatement.cs
source/Databricks/source/SqlStatementExecution.UnitTests/AppSettings/DatabricksSqlStatementOptionsTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/Exceptions/DatabricksExceptionTests.cs
source/Databricks/source/SqlStatementExecution.UnitTests/Fixtures/HealthChecksFixture.cs
source/Databricks/source/SqlStatementExecution/DatabricksSqlStatementOptions.cs
source/Databricks/source/SqlStatementExecution/DatabricksSqlWarehouseQueryExecutor.cs
source/Databricks/source/SqlStatementExecution/Formats/ApacheArrowFormat.cs
source/Databricks/source/SqlStatementExecution/Formats/JsonArrayFormat.cs
source/Databricks/source/SqlStatementExecution/Formats/StronglyTypedApacheArrowFormat.cs
source/Databricks/source/SqlStatementExecution/IExecuteStrategy.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/Databricks/source/SqlStatementExecution/Statement/DatabricksStatementRequest.cs

Replace bogus Databricks SQL execution time-out implementation with the best practice and much more flexible usage of cancellation tokens.

fix: Replace bogus Databricks SQL execution time out implementation with cancellation tokens

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Diagnostics/HealthChecks/DatabricksJobsApiHealthCheck.cs
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/Diagnostics/HealthChecks/DatabricksSqlStatementApiHealthCheck.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Add try-catch in health checks to avoid reporting both unhealthy states and logging exceptions.
The wholesale subsystem is experiencing transient exceptions, which don't render the application unhealthy but cause a lot of operations noise. This PR removes or reduces the noise, but is not a replacement for looking into the transient exceptions.

fix: Add try-catch in health checks

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/DatabricksStatementsTests.cs
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/Statements/AtLeast10SecStatement.cs
source/Databricks/source/SqlStatementExecution.IntegrationTests/Fixtures/DatabricksSqlWarehouseFixture.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/Databricks/source/SqlStatementExecution/Statement/DatabricksStatementRequest.cs

With the introduction of `CancellationToken` it is possible to cancel a statement that is sent to a Databricks cluster.
If a request is cancelled with a token then the statement continues to execute on the cluster. This PR sends a cancellation request to the cluster for the current statement.
Input needed:
How can this be tested? I have not be able to find a good way to test it.

Cancel statement if token cancellation is requested

---

.github/workflows/testcommon-bundle-publish.yml
source/TestCommon/source/FunctionApp.TestCommon.Tests/Fixtures/AzuriteManagerFixture.cs

⚠️ To force an update and release TestCommon, we have made a small change in the publishing workflow. Version 5.1.0 was never released, which is shy we don't need to update release notes and version.
It seems there is a bug i az cli v2.59.0 so we will try to downgrade to v2.58.0 (is handled in the reusable action)
See https://github.com/Azure/login/issues/372#issuecomment-2056289617

Downgrade az cli version

---

.github/CODEOWNERS

Add Team Mosaic as CODEOWNERS, since they now are responsible for the `geh-core` package
- ~~[ ] Release notes are updated~~
- ~~[ ] Package version is updated~~
- ~~[ ] Public types and methods are documented~~
- ~~[ ] Tests are implemented and executed locally~~

chore: Add Team Mosaic as codeowners

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/DatabricksStatementsTests.cs
source/Databricks/source/SqlStatementExecution/Formats/IArrowArrayExtensions.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

Add support for StructArray from Databricks SQL API in ApacheArrow format.
A query in this format
``` sql
SELECT * FROM VALUES
('Centrum', array(struct(5, 'd'), struct(7, 'z'))),
('Zen', array(struct(1, 'a'), struct(2, 'b'))) as data(name, ts)
```
will produce a dynamic type in C# that when serialised to JSON will look like this:
``` json
[
{
"name": "Centrum",
"ts": [
{
"col1": 5,
"col2": "d"
},
{
"col1": 7,
"col2": "z"
}
]
},
{
"name": "Zen",
"ts": [
{
"col1": 1,
"col2": "a"
},
{
"col1": 2,
"col2": "b"
}
]
}
]
```

Simple implementation for StructArray

---

source/Logging/documents/release-notes/release-notes.md
source/Logging/source/Logging/Logging.csproj
source/Logging/source/LoggingMiddleware/LoggingMiddleware.csproj
source/Logging/source/LoggingMiddleware/Registration.cs

Mark Azure Functions related logging extensions as obsolete.

Logging: Mark Azure Functions related logging extensions as obsolete

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/FunctionApp.TestCommon.Tests/FunctionApp.TestCommon.Tests.csproj
source/TestCommon/source/FunctionApp.TestCommon.Tests/Integration/Azurite/AzuriteManagerTests.cs
source/TestCommon/source/FunctionApp.TestCommon/Azurite/AzuriteManager.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon.Tests/TestCommon.Tests.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

When using azurite we see a lot of noise in the console and test logs. This PR enables azurite to run silentyl by default, but still allow developers to choose to output the log as previously.

refac: Enable AzuriteManager to run azurite silently

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution.IntegrationTests/Client/ObjectCreationTests.cs
source/Databricks/source/SqlStatementExecution/Formats/Reflections.cs
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj

The object creation did not support null-values.
With this change it can assign null-values to properties.

Support nullable parameters

---

source/Databricks/documents/release-notes/release-notes.md
source/Databricks/source/Jobs/Jobs.csproj
source/Databricks/source/SqlStatementExecution/SqlStatementExecution.csproj
source/Databricks/source/SqlStatementExecution/Statement/DatabricksStatementRequest.cs

fix: Overflow of backoff value.

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.Tests/WebApp.Tests.csproj
source/App/source/WebApp/WebApp.csproj

chore: Upgrade NuGet packages in App

---

source/App/documents/registrations/swagger-api-version.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.WebApi.Tests/Integration/SwaggerOpenApiTests.cs
source/App/source/ExampleHost.WebApi01/Startup.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/Extensions/DependencyInjection/OpenApiExtensions.cs
source/App/source/WebApp/WebApp.csproj

This PR will address the issue with Swagger generating `SchemaIds` for class'es with the same name eg: `MeteringPoint`. 
Swagger supports full namespace when generating `SchemaIds`, which can be setup when adding the configuration.
Verified on this PR: https://github.com/Energinet-DataHub/opengeh-edi/pull/1574

feat: full namespace support for Swagger generating SchemaIds

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/Configuration/IntegrationTestConfiguration.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Updated the configuration key from "**AZURE-EVENTHUB-NAMESPACE**" to "**AZURE-EVENTHUB-NAMESPACE-PREMIUM**" in `IntegrationTestConfiguration`. This new resource enables us to have up to 100 event hubs at the same time, instead of 10 (which is the current maximum).

test: Update integration test Event Hub namespace to use new premium resource

---

source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Tests/Common.Tests.csproj
source/App/source/Common/Common.csproj
source/App/source/ExampleHost.FunctionApp.Tests/ExampleHost.FunctionApp.Tests.csproj
source/App/source/ExampleHost.FunctionApp01/ExampleHost.FunctionApp01.csproj
source/App/source/ExampleHost.FunctionApp02/ExampleHost.FunctionApp02.csproj
source/App/source/ExampleHost.WebApi.Tests/ExampleHost.WebApi.Tests.csproj
source/App/source/ExampleHost.WebApi03/ExampleHost.WebApi03.csproj
source/App/source/FunctionApp.Tests/FunctionApp.Tests.csproj
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp.Tests/WebApp.Tests.csproj
source/App/source/WebApp/WebApp.csproj

Update test apps to prove which NuGet package versions we can use for .NET 9 in combination with Azure Functions Core Tools.
Important to notice is the following:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.1" />
```
Currently we cannot start the functions apps if we use:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.2" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.2" />
```
See also: https://github.com/Azure/azure-functions-host/issues/10575#issuecomment-2822580398

chore: NuGet packages for App packages

---

source/TestCommon/documents/release-notes/release-notes.md
source/TestCommon/source/DurableFunctionApp.TestCommon/DurableFunctionApp.TestCommon.csproj
source/TestCommon/source/FunctionApp.TestCommon/AppConfiguration/AppConfigurationManager.cs
source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj
source/TestCommon/source/TestCommon/TestCommon.csproj

Add setting name that we can use to disable Azure App Configuration provider in integration tests
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/712

TestCommon: Disable Azure App Configuration provider

---

source/App/App.sln
source/App/documents/documentation.md
source/App/documents/registrations/subsystem-authentication.md
source/App/documents/registrations/token-credential.md
source/App/documents/release-notes/release-notes.md
source/App/source/Common.Abstractions/Common.Abstractions.csproj
source/App/source/Common.Tests/Extensions/DependencyInjection/IdentityExtensionsTests.cs
source/App/source/Common.Tests/Identity/AuthorizationHeaderProviderTests.cs
source/App/source/Common.Tests/Identity/TokenCredentialFactoryTests.cs
source/App/source/Common.Tests/Identity/TokenCredentialProviderTests.cs
source/App/source/Common/Common.csproj
source/App/source/Common/Extensions/DependencyInjection/IdentityExtensions.cs
source/App/source/Common/Identity/TokenCredentialFactory.cs
source/App/source/Common/Identity/TokenCredentialProvider.cs
source/App/source/ExampleHost.FunctionApp.Tests/Fixtures/ExampleHostsFixture.cs
source/App/source/ExampleHost.FunctionApp01/Program.cs
source/App/source/ExampleHost.WebApi.Tests/Fixtures/ExampleHostFixture.cs
source/App/source/FunctionApp/Extensions/Builder/ConfigurationBuilderExtensions.cs
source/App/source/FunctionApp/FunctionApp.csproj
source/App/source/WebApp/Extensions/Builder/ConfigurationBuilderExtensions.cs
source/App/source/WebApp/WebApp.csproj

Implement `TokenCredentialFactory` so we encapsulate the creation of token credentials, and avoid instantiating `DefaultAzureCredential` when running in Azure.
Implement `TokenCredentialProvider` and matching extension `TokenCredentialProvider`. The `TokenCredentialProvider` uses `TokenCredentialFactory` to create the token credential it provides. By registering `TokenCredentialProvider` other service registration extension can easily get access to `TokenCredentialProvider` and its `Credential`. Thereby we can reduce the places where we might otherwise create separate token credential instanses.
Part of: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/402

refac: Implement a token credential factory
